local MULTI_MOD = {
	NAME = "ONLINE MULTIPLAYER",
	TIP = "<c:FF8411>ONLINE MULTIPLAYER</c>\nEnables multiplayer over a TCP connection.\Advanced options become available when you launch the game.",
	BUTTON_HOST = "HOST",
	BUTTON_JOIN = "JOIN",
	BUTTON_LOCAL = "OFFLINE PLAY",
	TITLE_SETUP = "SETUP ONLINE MULTIPLAYER",
	TITLE_HOST = "HOST GAME",
	TITLE_JOIN = "JOIN GAME",
	BODY_SETUP = "Click Host to setup a game for others to join.",
	BODY_HOST = "Send the ip, port, and optional password to those you wish to join the game.",
	BODY_JOIN = "Enter the ip, port, and password the host sent to you.",
	CONNECTION_FAILED = "CONNECTION FAILED",
	RETRY = "RETRY",
	PASSWORD_REJECTED = "Password Incorrect.",
	WAITING_JOINING = "Waiting to join game...",
	WAITING_PASSWORD = "Waiting for password verification...",
	CONNECTING = "CONNECTING",
	CONNECTING_BODY = "Connecting...",
	CONNECTION_TIMING_OUT = "Waiting for response...",
	CONTINUE_HOST = "HOST GAME",
	SOCKET_VERSION_REQUIRED = "Socket version required:",
	CURRENT_SOCKET_VERSION = "Current socket version:",
}

return MULTI_MOD